[theme]
primaryColor = "#1a4d7c"
backgroundColor = "#f1f5f9"
secondaryBackgroundColor = "#ffffff"
textColor = "#1e293b"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
